//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Team1732ScoutingWebForm
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MyDBContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MyDBContainer object using the connection string found in the 'MyDBContainer' section of the application configuration file.
        /// </summary>
        public MyDBContainer() : base("name=MyDBContainer", "MyDBContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyDBContainer object.
        /// </summary>
        public MyDBContainer(string connectionString) : base(connectionString, "MyDBContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyDBContainer object.
        /// </summary>
        public MyDBContainer(EntityConnection connection) : base(connection, "MyDBContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Match_Info> Match_Info
        {
            get
            {
                if ((_Match_Info == null))
                {
                    _Match_Info = base.CreateObjectSet<Match_Info>("Match_Info");
                }
                return _Match_Info;
            }
        }
        private ObjectSet<Match_Info> _Match_Info;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Match_Info EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMatch_Info(Match_Info match_Info)
        {
            base.AddObject("Match_Info", match_Info);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyDB", Name="Match_Info")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Match_Info : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Match_Info object.
        /// </summary>
        /// <param name="pK">Initial value of the PK property.</param>
        /// <param name="team">Initial value of the Team property.</param>
        /// <param name="match">Initial value of the Match property.</param>
        public static Match_Info CreateMatch_Info(global::System.Int32 pK, global::System.Int32 team, global::System.Int32 match)
        {
            Match_Info match_Info = new Match_Info();
            match_Info.PK = pK;
            match_Info.Team = team;
            match_Info.Match = match;
            return match_Info;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PK
        {
            get
            {
                return _PK;
            }
            set
            {
                if (_PK != value)
                {
                    OnPKChanging(value);
                    ReportPropertyChanging("PK");
                    _PK = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PK");
                    OnPKChanged();
                }
            }
        }
        private global::System.Int32 _PK;
        partial void OnPKChanging(global::System.Int32 value);
        partial void OnPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Team
        {
            get
            {
                return _Team;
            }
            set
            {
                OnTeamChanging(value);
                ReportPropertyChanging("Team");
                _Team = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Team");
                OnTeamChanged();
            }
        }
        private global::System.Int32 _Team;
        partial void OnTeamChanging(global::System.Int32 value);
        partial void OnTeamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Match
        {
            get
            {
                return _Match;
            }
            set
            {
                OnMatchChanging(value);
                ReportPropertyChanging("Match");
                _Match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Match");
                OnMatchChanged();
            }
        }
        private global::System.Int32 _Match;
        partial void OnMatchChanging(global::System.Int32 value);
        partial void OnMatchChanged();

        #endregion

    
    }

    #endregion

    
}
